### ISSUE TITLE
Buggerino: legkisebb méretben távolról megölt az enemy

### ISSUE THREAD

**Issue by kadam03** [Fork-on-the-Table-Collective/farty-little-things#105]
olyan, mintha legkisebb állapotban az ellenfelek perception areája megölne
(fixen reprodukálható, on my PíCí)

reprod: (test_map)

1. érd el hogy a legkisebb méretű legyél
2. szaladj oda a telefonhoz
3. legközelebbi szörny kinyír

![Image](https://github.com/user-attachments/assets/2d91381f-60be-4d55-8183-b0686e88b990)

**Comment by GuBee33** [comment]
done
