### ISSUE TITLE
Sound design - Produce assets

### ISSUE THREAD

**Issue by vmworks** [Fork-on-the-Table-Collective/farty-little-things#11]
**_Produced:_** 

- ambience (sewer)  _--> draft committed (sewer_ambience_mixdown)_ -> also covers environmental sounds
- environment (sewer)  _--> currently ambience covers this_ --> can be separate assets based on request
- enemy unit (presence)
    > fly  _--> draft committed_ (enemy_unit_fly)
    > cockroach  _--> draft committed_ (enemy_unit_cockroach)
    > rat  _--> draft committed_ (enemy_unit_rat)
    > player unit sebződés  _--> draft committed (enemy_unit_attack)_
- Player unit
    > footsteps  _--> draft committed_ (footsteps_basic)
    > kaki gyűjtés (upgrade)  _--> draft committed_ (kaki_upgrade)
    > kaki vesztés (downgrade)  _--> draft committed_ (kaki_downgrade)
    > item felszedése  _--> draft committed_ (item_pickup)
    > step on glass  _--> draft committed_ (player_step_on_glass)
    > walk in green trutyi  _--> draft committed_ (player_step_in_sewage_water)
    > interact w/ old phone   _--> draft committed_ (player_interact_old_phone)
- Menu
    > hover over button  _--> draft committed_ (menu_button_hover)
    > click button  _--> draft committed_ (menu_button_click)
    > in-game menu pop-up (kaki bubbles)  _--> draft committed_ (menu_ingame_popup)
- Gameplay
    > win condition - end game (nature waterfall + heavenly choir, harp)  _--> draft committed_ (endgame_victory_sound_...)
    > win condition after map (toilet flush sound)  _--> draft committed_ (win_sound_flush)
    > defeat condition after map (splat sound)  _--> draft committed_ (defeat_sound_splat)

_**To be produced:**_

- Player unit
    > interact w/ old computer  **--> to be produced** (Attila)
- Menu
    > menu music **--> to be produced** (Balázs)
- Gameplay
    > gameplay music  **--> to be produced** (Balázs)
- other characters
    > voiceovers for story  **--> to be produced** (Attila)

**Additional:**
_- audio mastering based on overall sound quality during gameplay test_

**Comment by GuBee33** [comment]
ha kész a #156 akkor szerintem megcsinálom ezt is

**Comment by GuBee33** [comment]
closes #99
